export const restorationTranslations = {
 en: {
  courses:'Courses', coursesTitle:'Explore Our Courses', coursesIntro:'Find your starting point in Qur’an, Tajweed, and Arabic. Explore each course, then choose a learning plan with your instructor.', details:'View course details', back:'Back to courses', overview:'Course overview', learn:'What you’ll work on', features:'How you’ll learn', who:'Who is this course for?', format:'Lesson format', individual:'Live one-to-one lessons', schedule:'Lesson schedule', arranged:'Agreed after your assessment', level:'Your starting point', tailored:'Matched to your level', goals:'Learning goals', courseImage:'Qur’an and Arabic learning at Salsabela Academy', related:'Explore another course', pricing:'Plans & Fees', pricingTitle:'A learning plan that fits you', pricingIntro:'Your course, lesson frequency, and schedule are discussed after your free assessment. Contact the academy for your plan and current fees before enrolling.', pricingNoRates:'No payment is requested through this page.', pricingStep1:'Tell us your goals', pricingStep2:'Discuss your schedule', pricingStep3:'Review your learning plan and fees', quickLinks:'Explore Salsabela', getStarted:'Start your journey', aboutTitle:'Personal guidance. Meaningful learning.', aboutIntro:'A focused space to learn the Qur’an and Arabic, one step at a time.', mission:'Our approach', missionBody:'Your starting point matters. We build lessons around your current understanding, leave room for questions, and practise the skills you need to move forward.', values:'Learning with care', value1:'Patient guidance', value1Body:'Ask questions and practise with direct support from your instructor.', value2:'Clear next steps', value2Body:'Know what you are working on and what to practise between lessons.', value3:'A sustainable routine', value3Body:'Agree on a schedule that works with your daily life and timezone.', contactHelp:'Let’s find your next step', contactHelpBody:'For a new course, use the free assessment application. For a question about the academy or your studies, send a message here.', noVideo:'Explore the courses', loading:'Loading this page…', retry:'Try again', pageError:'This page could not load. Check your connection and try again.',
  'quran-reading':{who:'Beginners and learners who want to improve the accuracy and confidence of their Qur’an reading.',learn:['Recognise Arabic letters and vowel marks.','Practise clear pronunciation and connected reading.','Build fluency through guided recitation.'],features:['Start with an assessment of your reading.','Practise selected passages with personal correction.','Agree on suitable practice between lessons.']},
  tajweed:{who:'Learners who can read Arabic and want to improve their recitation through the practical study of Tajweed.',learn:['Develop awareness of articulation points.','Study relevant Tajweed rules step by step.','Recognise recitation errors and practise corrections.'],features:['Listen, recite, and receive direct feedback.','Apply each rule to selected Qur’anic passages.','Review earlier material as you progress.']},
  'arabic-language':{who:'Learners who want to develop their Arabic reading, vocabulary, comprehension, and communication.',learn:['Build reading and writing foundations.','Expand useful vocabulary and sentence patterns.','Practise comprehension and everyday communication.'],features:['Begin at a level suited to your experience.','Combine explanations with guided exercises.','Use regular practice to strengthen your skills.']}
 },
 ar: {
  courses:'الدورات',coursesTitle:'استكشف دوراتنا',coursesIntro:'اختر نقطة انطلاقك في القرآن الكريم والتجويد واللغة العربية. تعرّف على تفاصيل كل دورة، ثم اتفق مع معلمك على خطة تناسبك.',details:'عرض تفاصيل الدورة',back:'العودة إلى الدورات',overview:'نبذة عن الدورة',learn:'ما الذي ستتدرّب عليه؟',features:'كيف ستتعلّم؟',who:'لمن هذه الدورة؟',format:'نظام الدروس',individual:'دروس فردية مباشرة',schedule:'مواعيد الدروس',arranged:'تُحدَّد بعد التقييم',level:'نقطة البداية',tailored:'بما يناسب مستواك',goals:'أهداف التعلّم',courseImage:'تعلّم القرآن الكريم واللغة العربية في أكاديمية سلسبيلا',related:'استكشف دورة أخرى',pricing:'الخطط والرسوم',pricingTitle:'خطة تعلّم تناسبك',pricingIntro:'نتفق معك على الدورة وعدد الدروس ومواعيدها بعد التقييم المجاني. تواصل مع الأكاديمية لمعرفة خطتك والرسوم الحالية قبل التسجيل.',pricingNoRates:'لا نطلب أي دفعة مالية من خلال هذه الصفحة.',pricingStep1:'أخبرنا بأهدافك',pricingStep2:'ناقش المواعيد المناسبة',pricingStep3:'راجع خطة التعلّم ورسومها',quickLinks:'استكشف سلسبيلا',getStarted:'ابدأ رحلتك',aboutTitle:'إرشاد شخصي وتعلّم هادف',aboutIntro:'مساحة لتعلّم القرآن الكريم واللغة العربية، خطوة بخطوة.',mission:'منهجنا في التعليم',missionBody:'نقطة البداية مهمة. نبني الدروس على ما تعرفه الآن، ونترك مساحة لأسئلتك، ونتدرّب معك على المهارات التي تحتاجها للتقدّم.',values:'تعلّم بعناية',value1:'إرشاد بصبر',value1Body:'اسأل وتدرّب مع دعم مباشر من معلمك.',value2:'خطوات واضحة',value2Body:'اعرف ما تتعلّمه وما تحتاج إلى مراجعته بين الدروس.',value3:'روتين يناسب حياتك',value3Body:'اتفق على مواعيد تراعي يومك ومنطقتك الزمنية.',contactHelp:'لنحدّد خطوتك القادمة',contactHelpBody:'لبدء دورة جديدة، استخدم طلب التقييم المجاني. وللاستفسار عن الأكاديمية أو دراستك، أرسل رسالتك من هنا.',noVideo:'استكشف الدورات',loading:'جارٍ تحميل الصفحة…',retry:'حاول مرة أخرى',pageError:'تعذّر تحميل الصفحة. تحقق من اتصالك ثم حاول مرة أخرى.',
  'quran-reading':{who:'للمبتدئين ولمن يرغب في تحسين دقة قراءته للقرآن الكريم وثقته في التلاوة.',learn:['التعرّف على الحروف العربية وعلامات الضبط.','التدرّب على النطق الواضح ووصل الكلمات.','بناء الطلاقة من خلال التلاوة الموجّهة.'],features:['البدء بتقييم مستوى القراءة.','قراءة مقاطع مختارة مع التصحيح الفردي.','تحديد تدريب مناسب بين الدروس.']},
  tajweed:{who:'لمن يستطيع قراءة العربية ويريد تحسين تلاوته بدراسة التجويد وتطبيقه.',learn:['التعرّف على مخارج الحروف.','دراسة أحكام التجويد تدريجيًا.','تمييز أخطاء التلاوة والتدرّب على تصحيحها.'],features:['الاستماع والتلاوة وتلقّي الملاحظات مباشرة.','تطبيق كل حكم على مواضع مختارة من القرآن.','مراجعة ما سبق تعلّمه أثناء التقدّم.']},
  'arabic-language':{who:'لمن يريد تطوير القراءة والمفردات والفهم والتواصل باللغة العربية.',learn:['بناء أساس في القراءة والكتابة.','زيادة المفردات وتعلّم تركيب الجمل.','التدرّب على الفهم والتواصل اليومي.'],features:['البداية من مستوى يناسب خبرتك.','الجمع بين الشرح والتدريبات الموجّهة.','تقوية المهارات بالممارسة المنتظمة.']}
 }
};
