export const issueKinds = ['reminder', 'absence_first', 'absence_second', 'absence_third', 'apologized', 'early_leave', 'instructor_late'] as const;
export const followupTranslations = {
  en: {
    adjustPlan: 'Adjust the learning plan', adjustPlanHint: 'Use this when lesson goals or practice methods need an adjustment.',
    studentsTitle: 'Your students', studentsIntro: 'A clear view of each student, their lessons, and your follow-up.', search: 'Search by name or email', all: 'All', details: 'Student details', nextLesson: 'Next lesson', noNext: 'No upcoming lesson', completed: 'Completed lessons', attendance: 'Recorded attendance', timezone: 'Timezone', programs: 'Enrolled courses', noPrograms: 'No enrollment yet', lessons: 'Student lessons', reschedule: 'Reschedule', report: 'Lesson report', issue: 'Lesson update', covered: 'What was covered?', coveredHint: 'Describe the material taught from your own device. No syllabus upload is needed.', behavior: 'Behavior quality', participation: 'Participation quality', comment: 'Additional comment', send: 'Send to student', sending: 'Sending…', sent: 'Saved and sent to academy notifications. Phone delivery requires an enabled subscription.', reminder: 'Send reminder to student', absence_first: 'Student absence (1st time)', absence_second: 'Student absence (2nd time)', absence_third: 'Student absence (3rd time or more)', apologized: 'Student apologized and will not attend', early_leave: 'Student requested early leave', instructor_late: "I'll be late", chooseIssue: 'Choose a lesson update', history: 'Reports and lesson updates', noHistory: 'No reports or updates yet', reportReceived: 'Your lesson report', issueReceived: 'A lesson update', start: 'Starts', end: 'Ends', saveSchedule: 'Save new time', browserTime: 'Enter times in your device timezone:', reportFuture: 'Reports can be submitted after the lesson starts.', failed: 'Could not save. Please try again.', invalid: 'Check the entered values.', missing: 'This lesson is no longer available.', limited: 'Too many updates. Try again later.', conflict: 'The request conflicts with an earlier update. Refresh and try again.', cancelled: 'Cancelled lessons cannot receive updates.', empty: 'No students match your search.', active: 'Active', suspended: 'Suspended', invited: 'Invited', scheduleTitle: 'Your academy schedule', scheduleIntro: 'Lessons and assessments, in one place.', today: 'Today', previous: 'Previous period', next: 'Next period', month: 'Month', week: 'Week', day: 'Day', list: 'List', assessment: 'Assessment', lesson: 'Lesson', allTypes: 'Lessons and assessments', noEvents: 'No sessions in this period', open: 'Open session', create: 'Schedule a lesson', rating1: 'Needs support', rating2: 'Developing', rating3: 'Good', rating4: 'Very good', rating5: 'Excellent', quality: 'Quality', phoneHint: 'Phone notifications are sent only to devices where the student enabled them.', minuteHint: 'Optional explanation or delay in minutes', profile: 'Student profile', scheduleConflict: 'This time overlaps another lesson or assessment.', savedSchedule: 'The lesson was rescheduled. Its integrations are queued for synchronization.',
  },
  ar: {
    adjustPlan: 'تعديل خطة التعلم', adjustPlanHint: 'حدّد هذا الخيار إذا احتاج الطالب إلى تغيير أهداف الحصص أو طريقة التدريب.',
    studentsTitle: 'طلاب الأكاديمية', studentsIntro: 'كل طالب، وحصصه، ومتابعتك له في مكان واضح ومنظم.', search: 'ابحث بالاسم أو البريد الإلكتروني', all: 'الكل', details: 'تفاصيل الطالب', nextLesson: 'الحصة القادمة', noNext: 'لا توجد حصة قادمة', completed: 'الحصص المكتملة', attendance: 'سجل الحضور', timezone: 'المنطقة الزمنية', programs: 'الدورات الملتحق بها', noPrograms: 'لم يلتحق بدورة بعد', lessons: 'حصص الطالب', reschedule: 'إعادة الجدولة', report: 'تقرير الحصة', issue: 'تنبيه الحصة', covered: 'ماذا تمت دراسته؟', coveredHint: 'اكتب ما درّسته من جهازك؛ لا تحتاج إلى رفع المنهج.', behavior: 'تقييم السلوك', participation: 'تقييم المشاركة', comment: 'تعليق إضافي', send: 'إرسال إلى الطالب', sending: 'جارٍ الإرسال…', sent: 'تم الحفظ والإرسال إلى إشعارات الأكاديمية. إشعار الهاتف يتطلب تفعيل الاشتراك.', reminder: 'إرسال تذكير للطالب', absence_first: 'غياب الطالب للمرة الأولى', absence_second: 'غياب الطالب للمرة الثانية', absence_third: 'غياب الطالب للمرة الثالثة أو أكثر', apologized: 'اعتذر الطالب ولن يحضر', early_leave: 'طلب الطالب المغادرة مبكرًا', instructor_late: 'سأتأخر عن الحصة', chooseIssue: 'اختر نوع التنبيه', history: 'التقارير وتنبيهات الحصص', noHistory: 'لا توجد تقارير أو تنبيهات بعد', reportReceived: 'تقرير حصتك', issueReceived: 'تنبيه بخصوص الحصة', start: 'البداية', end: 'النهاية', saveSchedule: 'حفظ الموعد الجديد', browserTime: 'أدخل المواعيد حسب المنطقة الزمنية لجهازك:', reportFuture: 'يمكن إرسال التقرير بعد بدء الحصة.', failed: 'تعذر الحفظ. حاول مرة أخرى.', invalid: 'راجع البيانات المدخلة.', missing: 'هذه الحصة لم تعد متاحة.', limited: 'أرسلت تحديثات كثيرة. حاول لاحقًا.', conflict: 'يتعارض الطلب مع تحديث سابق. حدّث الصفحة وحاول مجددًا.', cancelled: 'لا يمكن إرسال تحديثات لحصة ملغاة.', empty: 'لا يوجد طلاب يطابقون البحث.', active: 'نشط', suspended: 'موقوف', invited: 'تمت دعوته', scheduleTitle: 'جدول الأكاديمية', scheduleIntro: 'الحصص والتقييمات، في مكان واحد.', today: 'اليوم', previous: 'الفترة السابقة', next: 'الفترة التالية', month: 'شهر', week: 'أسبوع', day: 'يوم', list: 'قائمة', assessment: 'تقييم', lesson: 'حصة', allTypes: 'الحصص والتقييمات', noEvents: 'لا توجد مواعيد في هذه الفترة', open: 'عرض الموعد', create: 'جدولة حصة', rating1: 'يحتاج دعمًا', rating2: 'في تطور', rating3: 'جيد', rating4: 'جيد جدًا', rating5: 'ممتاز', quality: 'التقييم', phoneHint: 'تصل إشعارات الهاتف للأجهزة التي فعّل الطالب الإشعارات عليها فقط.', minuteHint: 'توضيح اختياري أو مدة التأخر بالدقائق', profile: 'ملف الطالب', scheduleConflict: 'يتداخل هذا الموعد مع حصة أو تقييم آخر.', savedSchedule: 'تم تغيير موعد الحصة وإضافة تحديث خدماتها إلى قائمة المزامنة.',
  },
};
