/** Owner's nine original courses recovered from repository commit 6287fc4, server/routes.ts.
 * This is reviewed academy content, not demo users or fabricated enrolments.
 * Hifz copy adjusted only to avoid multiple-instructor/accreditation claims.
 */
import type {InsertCourse} from './schema';
export const originalCourses = [
    {
      title: "Quran Reading for Beginners",
      titleAr: "تلاوة القرآن للمبتدئين",
      description: "Learn to read the Holy Quran from scratch with proper pronunciation (Makharij).",
      descriptionAr: "تعلّم قراءة القرآن الكريم من الصفر مع نطق صحيح للحروف من مخارجها الصحيحة، خطوة بخطوة.",
      imageUrl: "https://i.postimg.cc/3RBgfgjF/Quran-Reading-for-Beginners.jpg",
      imageUrlAr: "https://i.postimg.cc/Y931D1ND/tlawt-alqran-llmbtdyyn.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "Beginner",
      levelAr: "مبتدئ",
      },
      {
      title: "Advanced Tajweed Rules",
      titleAr: "أحكام التجويد المتقدمة",
      description: "Master the rules of Tajweed to recite the Quran exactly as it was revealed.",
      descriptionAr: "أتقن أحكام التجويد الكاملة لتتلو القرآن الكريم كما أُنزل على النبي ﷺ بإتقان واحترافية.",
      imageUrl: "https://i.postimg.cc/Kc0PnD8R/Advanced-Tajweed-Rules.jpg",
      imageUrlAr: "https://i.postimg.cc/fW8cxfRt/ahkam-altjwyd-almtqdmt.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "Advanced",
      levelAr: "متقدم",
      },
      {
      title: "Quran Memorization (Hifz)",
      titleAr: "حفظ القرآن الكريم",
      description: "A structured program to help you memorize the Holy Quran with guidance from your academy instructor.",
      descriptionAr: "برنامج منظم ومتدرّج لمساعدتك على حفظ القرآن الكريم بإشراف معلم الأكاديمية.",
      imageUrl: "https://i.postimg.cc/L6q1jdWb/Quran-Memorization-(Hifz).jpg",
      imageUrlAr: "https://i.postimg.cc/X7Ty8HMm/hfz-alqran-alkrym.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "All Levels",
      levelAr: "جميع المستويات",
      },
      {
      title: "Arabic Language Mastery",
      titleAr: "إتقان اللغة العربية",
      description: "Comprehensive Arabic language course focusing on reading, writing, and conversational skills.",
      descriptionAr: "دورة عربية شاملة تُركّز على القراءة والكتابة والمحادثة اليومية وبناء المفردات والقواعد.",
      imageUrl: "https://i.postimg.cc/43GHCYxM/Arabic-Language-Mastery.jpg",
      imageUrlAr: "https://i.postimg.cc/43GHCY3g/atqan-allght-al%CA%BFrbyt.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "Intermediate",
      levelAr: "متوسط",
      },
      {
      title: "Basics of Islam",
      titleAr: "أساسيات الإسلام",
      description: "An essential introduction to Islamic beliefs, the five pillars, and everyday worship practices for new Muslims and seekers.",
      descriptionAr: "مدخل أساسي شامل للعقيدة الإسلامية وأركان الإسلام الخمسة والعبادات اليومية للمسلمين الجدد وطالبي المعرفة.",
      imageUrl: "https://i.postimg.cc/KjC40zVX/Basics-of-islam.jpg",
      imageUrlAr: "https://i.postimg.cc/Y0Tjd9VB/t%CA%BFlm-asasyat-alaslam.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "Beginner",
      levelAr: "مبتدئ",
      },
      {
      title: "Islamic Jurisprudence (Fiqh)",
      titleAr: "الفقه الإسلامي",
      description: "A comprehensive study of Islamic law covering worship, transactions, and rulings for daily life based on classical scholarship.",
      descriptionAr: "دراسة متعمقة في الفقه الإسلامي تشمل العبادات والمعاملات وأحكام الحياة اليومية استناداً إلى الفقه الكلاسيكي.",
      imageUrl: "https://i.postimg.cc/HnrV056J/Islamic-Jurisprudence-(Fiqh).jpg",
      imageUrlAr: "https://i.postimg.cc/MHnv0R9M/ahkam-alfqh-alaslamy.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "Advanced",
      levelAr: "متقدم",
      },
      {
      title: "On-demand Course",
      titleAr: "دورة حسب الطلب",
      description: "A fully tailored educational experience built around your unique goals, level, and learning style — spanning Quran, Arabic, Fiqh, Tafseer, and any Islamic science you need.",
      descriptionAr: "من خلال هذا البرنامج ستحصل على خطة تعليمية واضحة ومخصصة لك، تساعدك على التقدم في المجال الذي تحتاجه بطريقة منظمة وفعّالة تناسب مستواك وأهدافك.",
      imageUrl: "https://i.postimg.cc/0546kWNV/on-demand-course.jpg",
      imageUrlAr: "https://i.postimg.cc/HWNJYZLv/dwrt-hsb-altlb.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "All Levels",
      levelAr: "جميع المستويات",
      },
      {
      title: "Tafsir & Tadabbur",
      titleAr: "التفسير والتدبر",
      description: "The Tafsir & Tadabbur Course is a structured learning program designed to help students understand the meanings of the Holy Qur’an in a clear and simple way, while also reflecting deeply on its messages and applying them in daily life.",
      descriptionAr: "كورس التفسير والتدبر هو برنامج تعليمي يهدف إلى مساعدة الطالب على فهم آيات القرآن الكريم فهمًا صحيحًا، مع التعمق في معانيها وربطها بحياة المسلم اليومية.لا يقتصر هذا الكورس على التفسير التقليدي فقط، بل يركز أيضًا على التدبر العملي للآيات وكيفية تطبيقها في الواقع، ليكون القرآن منهج حياة وليس مجرد قراءة.يتم تقديم شرح يومي مبسط لآية واحدة أو مجموعة قصيرة من الآيات بطريقة سهلة وواضحة تناسب جميع المستويات.",
      imageUrl: "https://i.postimg.cc/XNrLLdfV/1quran-interpretation-and-reflection.jpg",
      imageUrlAr: "https://i.postimg.cc/qqK7Rj9k/kwrs-altfsyr-1waltdbr.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "All Levels",
      levelAr: "جميع المستويات",
      },
      {
      title: "Prophetic Hadith",
      titleAr: "الأحاديث النبوية",
      description: "The Prophetic Hadith Course is an educational program designed to connect students with the Prophetic Sunnah by explaining one Hadith per session. The course emphasizes a deep understanding of the Hadiths' meanings and their application in daily life, transforming the Sunnah from mere theoretical knowledge into practical, lived behavior in a Muslim's life.",
      descriptionAr: "كورس الأحاديث النبوية هو برنامج تعليمي يهدف إلى ربط الطالب بالسنة النبوية من خلال شرح حديث نبوي واحد كل حصة, يركز الكورس على الفهم العميق لمعاني الأحاديث وتطبيقها في الحياة اليومية، بحيث تتحول السنة النبوية من مجرد علم نظري إلى سلوك عملي ومعيش في حياة المسلم.",
      imageUrl: "https://i.postimg.cc/pV5rqLpb/1-course-of-prophetic-Hadith.jpg",
      imageUrlAr: "https://i.postimg.cc/v8xT3Zcd/1kwrs-alahadyth-alnbwyt.jpg",
      duration: "Based on student's level",
      durationAr: "حسب مستوى الطالب",
      classDetails: "30 min / 45 min / 1 hour per session",
      classDetailsAr: "٣٠ دقيقة أو ٤٥ دقيقة أو ساعة",
      price: "Based on package",
      level: "All Levels",
      levelAr: "جميع المستويات",
      },
  ] satisfies InsertCourse[];
