import { pgTable, jsonb, text, bigserial, serial, timestamp, varchar, integer, boolean, uniqueIndex, index, check, uuid, date } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
export * from "./integration-schema";

const timestamps = { createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() };

export const courses = pgTable("courses", { id: serial("id").primaryKey(), title: text("title").notNull(), titleAr: text("title_ar").notNull().default(""), description: text("description").notNull(), descriptionAr: text("description_ar").notNull().default(""), imageUrl: text("image_url").notNull(), imageUrlAr: text("image_url_ar").notNull().default(""), duration: text("duration").notNull(), durationAr: text("duration_ar").notNull().default(""), classDetails: text("class_details").notNull().default(""), classDetailsAr: text("class_details_ar").notNull().default(""), price: text("price").notNull(), level: text("level").notNull(), levelAr: text("level_ar").notNull().default("") });
export const inquiries = pgTable("inquiries", { id: serial("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull(), phone: varchar("phone", { length: 30 }), courseInterest: text("course_interest").notNull(), message: text("message"), status: text("status").notNull().default("pending"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const posts = pgTable("posts", { id: serial("id").primaryKey(), title: text("title").notNull(), content: text("content").notNull(), language: text("language").notNull().default("en"), coverImage: text("cover_image"), slug: text("slug").notNull().unique(), metaDescription: text("meta_description"), status: text("status").notNull().default("published"), ...timestamps }, (t) => [index("posts_status_idx").on(t.status)]);

export const users = pgTable("users", {
  id: serial("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull(), passwordHash: text("password_hash").notNull().default(""),
  role: text("role").notNull().default("student"), status: text("status").notNull().default("invited"), avatarUrl: text("avatar_url"), grade: text("grade"), phone: varchar("phone", { length: 30 }),
  emailVerifiedAt: timestamp("email_verified_at"), lastLoginAt: timestamp("last_login_at"), failedLoginAttempts: integer("failed_login_attempts").notNull().default(0), lockedUntil: timestamp("locked_until"),
  ...timestamps,
}, (t) => [uniqueIndex("users_email_normalized_idx").on(sql`lower(${t.email})`), check("users_role_check", sql`${t.role} in ('admin','student')`), check("users_status_check", sql`${t.status} in ('invited','active','suspended','archived')`)]);

export const studentProfiles = pgTable("student_profiles", {
  id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }).unique(), fullName: text("full_name").notNull(),
  phone: varchar("phone", { length: 30 }), country: varchar("country", { length: 100 }), timezone: varchar("timezone", { length: 80 }), preferredLanguage: varchar("preferred_language", { length: 10 }),
  ageGroup: text("age_group"), currentLevel: text("current_level"), learningGoals: text("learning_goals"), selectedProgram: text("selected_program"), availability: text("availability"), internalAdminNotes: text("internal_admin_notes"),
  emergencyContactName: text("emergency_contact_name"), emergencyContactPhone: varchar("emergency_contact_phone", { length: 30 }), ...timestamps,
}, (t) => [check("profile_age_group_check", sql`${t.ageGroup} is null or ${t.ageGroup} in ('child','teenager','adult')`)]);

export const platformApplications = pgTable("platform_applications", {
  id: serial("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull(), phone: varchar("phone", { length: 30 }), country: varchar("country", { length: 100 }), timezone: varchar("timezone", { length: 80 }), preferredLanguage: varchar("preferred_language", { length: 10 }), ageGroup: text("age_group"), requestedProgram: text("requested_program"), course: text("course"), currentExperience: text("current_experience"), learningGoals: text("learning_goals"), availability: text("availability"), requestedRole: text("requested_role").notNull().default("student"), status: text("status").$type<"new" | "contacted" | "assessment_booked" | "assessed" | "accepted" | "rejected" | "archived">().notNull().default("new"), adminNotes: text("admin_notes"), ...timestamps,
}, (t) => [index("applications_status_idx").on(t.status), index("applications_email_idx").on(t.email), uniqueIndex("applications_active_email_idx").on(sql`lower(${t.email})`).where(sql`${t.status} not in ('rejected','archived')`), check("application_role_check", sql`${t.requestedRole} = 'student'`), check("application_status_check", sql`${t.status} in ('new','contacted','assessment_booked','assessed','accepted','rejected','archived')`)]);
export const applications = platformApplications;

export const appointments = pgTable("appointments", { id: serial("id").primaryKey(), applicationId: integer("application_id").references(() => platformApplications.id, { onDelete: "set null" }), studentId: integer("student_id").references(() => users.id, { onDelete: "set null" }), appointmentType: text("appointment_type").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), originalTimezone: text("original_timezone"), status: text("status").notNull().default("requested"), zoomReference: text("zoom_reference"), googleCalendarEventReference: text("google_calendar_event_reference"), notes: text("notes"), ...timestamps }, (t) => [index("appointments_student_idx").on(t.studentId), index("appointments_application_idx").on(t.applicationId), check("appointment_status_check", sql`${t.status} in ('requested','confirmed','completed','cancelled','no_show')`), check("appointment_time_check", sql`${t.endsAt} > ${t.startsAt}`)]);

export const programs = pgTable("programs", { id: serial("id").primaryKey(), name: text("name").notNull().unique(), slug: text("slug").notNull().unique(), description: text("description"), isPublic: boolean("is_public").notNull().default(true), ...timestamps });
export const curriculumModules = pgTable("curriculum_modules", { id: serial("id").primaryKey(), programId: integer("program_id").notNull().references(() => programs.id, { onDelete: "cascade" }), title: text("title").notNull(), sortOrder: integer("sort_order").notNull().default(0), ...timestamps }, (t) => [index("curriculum_modules_program_idx").on(t.programId)]);
export const curriculumUnits = pgTable("curriculum_units", { id: serial("id").primaryKey(), moduleId: integer("module_id").notNull().references(() => curriculumModules.id, { onDelete: "cascade" }), title: text("title").notNull(), body: text("body"), sortOrder: integer("sort_order").notNull().default(0), ...timestamps });
export const enrollments = pgTable("enrollments", { id: serial("id").primaryKey(), studentId: integer("student_id").notNull().references(() => users.id, { onDelete: "cascade" }), programId: integer("program_id").notNull().references(() => programs.id, { onDelete: "restrict" }), status: text("status").notNull().default("active"), startedAt: timestamp("started_at").defaultNow(), completedAt: timestamp("completed_at"), ...timestamps }, (t) => [uniqueIndex("enrollments_student_program_idx").on(t.studentId, t.programId), check("enrollment_status_check", sql`${t.status} in ('active','paused','completed','withdrawn')`)]);
export const materials = pgTable("materials", { id: serial("id").primaryKey(), unitId: integer("unit_id").notNull().references(() => curriculumUnits.id, { onDelete: "cascade" }), title: text("title").notNull(), fileUrl: text("file_url"), googleDriveUrl: text("google_drive_url"), ...timestamps });
export const assignedMaterials = pgTable("assigned_materials", { id: serial("id").primaryKey(), enrollmentId: integer("enrollment_id").notNull().references(() => enrollments.id, { onDelete: "cascade" }), materialId: integer("material_id").notNull().references(() => materials.id, { onDelete: "cascade" }), assignedAt: timestamp("assigned_at").defaultNow().notNull(), ...timestamps }, (t) => [uniqueIndex("assigned_material_unique").on(t.enrollmentId, t.materialId)]);
export const progress = pgTable("student_progress", { id: serial("id").primaryKey(), enrollmentId: integer("enrollment_id").notNull().references(() => enrollments.id, { onDelete: "cascade" }), unitId: integer("unit_id").notNull().references(() => curriculumUnits.id, { onDelete: "cascade" }), completionStatus: text("completion_status").notNull().default("not_started"), completedAt: timestamp("completed_at"), ...timestamps }, (t) => [uniqueIndex("progress_enrollment_unit_idx").on(t.enrollmentId, t.unitId), check("progress_status_check", sql`${t.completionStatus} in ('not_started','in_progress','completed')`)]);

export const lessonSeries=pgTable('lesson_series',{id:serial('id').primaryKey(),actorId:integer('actor_id').notNull().references(()=>users.id),studentId:integer('student_id').notNull().references(()=>users.id),requestKey:uuid('request_key').notNull().unique(),payloadHash:text('payload_hash').notNull(),timezone:text('timezone').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()});
export const aiRequestUsage=pgTable('ai_request_usage',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull()});
export const lessons = pgTable("lessons", { seriesId:integer("series_id").references(()=>lessonSeries.id), id: serial("id").primaryKey(), studentId: integer("student_id").notNull().references(() => users.id, { onDelete: "cascade" }), programId: integer("program_id").references(() => programs.id, { onDelete: "set null" }), title: text("title").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }), endsAt: timestamp("ends_at", { withTimezone: true }), status: text("status").notNull().default("scheduled"), zoomReference: text("zoom_reference"), googleCalendarReference: text("google_calendar_reference"), attendance: text("attendance"), homework: text("homework"), feedback: text("feedback"), privateAdminNotes: text("private_admin_notes"), ...timestamps }, (t) => [index("lessons_student_idx").on(t.studentId), uniqueIndex("lessons_series_occurrence_idx").on(t.seriesId,t.startsAt).where(sql`${t.seriesId} is not null`), index("lessons_program_idx").on(t.programId), check("lesson_status_check", sql`${t.status} in ('scheduled','completed','cancelled')`), check("lesson_time_check", sql`${t.endsAt} is null or ${t.startsAt} is null or ${t.endsAt} > ${t.startsAt}`)]);

export const lessonFollowups = pgTable('lesson_followups', {
  id:bigserial('id',{mode:'number'}).primaryKey(), lessonId:integer('lesson_id').notNull().references(()=>lessons.id,{onDelete:'cascade'}), studentId:integer('student_id').notNull().references(()=>users.id,{onDelete:'cascade'}), actorId:integer('actor_id').references(()=>users.id,{onDelete:'set null'}), requestKey: uuid('request_key').notNull().unique(), payloadHash:text('payload_hash').notNull(), kind:text('kind').notNull(), issueKind:text('issue_kind'), covered:text('covered').notNull().default(''), adjustPlan:boolean('adjust_plan').notNull().default(false), behavior:integer('behavior'), participation:integer('participation'), comment:text('comment').notNull().default(''), createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
}, t=>[index('lesson_followup_student_idx').on(t.studentId,t.createdAt),index('lesson_followup_lesson_idx').on(t.lessonId,t.createdAt),check('followup_kind_check',sql`${t.kind} IN ('report','issue')`),check('followup_behavior_check',sql`${t.behavior} BETWEEN 1 AND 5`),check('followup_participation_check',sql`${t.participation} BETWEEN 1 AND 5`)]);

export const authSessions = pgTable("auth_sessions", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at").notNull(), revokedAt: timestamp("revoked_at"), ...timestamps }, (t) => [index("sessions_user_idx").on(t.userId)]);
export const passwordResetTokens = pgTable("password_reset_tokens", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at").notNull(), usedAt: timestamp("used_at"), ...timestamps });
export const invitations = pgTable("invitations", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at").notNull(), acceptedAt: timestamp("accepted_at"), ...timestamps }, (t) => [uniqueIndex("invitations_active_user_idx").on(t.userId).where(sql`${t.acceptedAt} is null`)]);
export const verificationTokens = pgTable("verification_tokens", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at").notNull(), usedAt: timestamp("used_at"), ...timestamps });

export const attendanceRecords = pgTable("attendance_records", { id: serial("id").primaryKey(), studentId: integer("student_id").notNull().references(() => users.id, { onDelete: "cascade" }), instructorId: integer("instructor_id").references(() => users.id, { onDelete: "set null" }), course: text("course").notNull(), sessionDate: timestamp("session_date", { withTimezone: true }).notNull(), status: text("status").notNull().default("present"), notes: text("notes"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const gradeRecords = pgTable("grade_records", { id: serial("id").primaryKey(), studentId: integer("student_id").notNull().references(() => users.id, { onDelete: "cascade" }), instructorId: integer("instructor_id").references(() => users.id, { onDelete: "set null" }), course: text("course").notNull(), assignment: text("assignment").notNull(), score: integer("score").notNull(), maxScore: integer("max_score").notNull().default(100), feedback: text("feedback"), gradedAt: timestamp("graded_at").defaultNow().notNull() });
export const messages = pgTable("messages", { requestKey:uuid("request_key"), id: serial("id").primaryKey(), senderId: integer("sender_id").notNull().references(() => users.id, { onDelete: "cascade" }), recipientId: integer("recipient_id").notNull().references(() => users.id, { onDelete: "cascade" }), subject: text("subject").notNull(), body: text("body").notNull(), readAt: timestamp("read_at"), createdAt: timestamp("created_at").defaultNow().notNull() }, (t) => [index("messages_recipient_idx").on(t.recipientId),uniqueIndex("messages_request_idx").on(t.senderId,t.requestKey).where(sql`${t.requestKey} is not null`),index("messages_conversation_idx").on(t.senderId,t.recipientId,t.id)]);
export const conversations = pgTable("conversations", { id: serial("id").primaryKey(), studentId: integer("student_id").notNull().references(() => users.id, { onDelete: "cascade" }), adminId: integer("admin_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...timestamps }, (t) => [uniqueIndex("conversation_pair_idx").on(t.studentId, t.adminId)]);
export const notifications = pgTable("notifications", { context:jsonb("context"), id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull(), body: text("body").notNull(), readAt: timestamp("read_at"), ...timestamps }, (t) => [index("notifications_user_idx").on(t.userId)]);

export const insertCourseSchema = createInsertSchema(courses).omit({ id: true });
export const insertInquirySchema = createInsertSchema(inquiries).omit({ id: true, status: true, createdAt: true }).extend({ name: z.string().min(2), email: z.string().email(), phone: z.string().optional().or(z.literal("")), courseInterest: z.string().min(1), message: z.string().optional().or(z.literal("")) });
export const insertPostSchema = createInsertSchema(posts).omit({ id: true, createdAt: true, updatedAt: true }).extend({ title: z.string().trim().min(1).max(200), content: z.string().trim().min(1).max(200000), language: z.enum(["en", "ar"]), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), coverImage: z.string().url().refine(v=>{try{const u=new URL(v);return u.protocol==="https:"&&!u.username&&!u.password;}catch{return false;}}).nullable().optional(), status: z.enum(["draft", "published"]) });
export type Course = typeof courses.$inferSelect; export type InsertCourse = z.infer<typeof insertCourseSchema>; export type Inquiry = typeof inquiries.$inferSelect; export type InsertInquiry = z.infer<typeof insertInquirySchema>; export type Post = typeof posts.$inferSelect; export type InsertPost = z.infer<typeof insertPostSchema>; export type User = typeof users.$inferSelect; export type PlatformApplication = typeof platformApplications.$inferSelect; export type AttendanceRecord = typeof attendanceRecords.$inferSelect; export type GradeRecord = typeof gradeRecords.$inferSelect; export type Message = typeof messages.$inferSelect;

// Phase 4 additive operational tables. Apply reviewed SQL migration explicitly.
export const academySettings = pgTable('academy_settings', {id:integer('id').primaryKey().default(1),publicName:text('public_name').notNull().default('Salsabela Academy'),contactEmail:text('contact_email').notNull().default(''),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[check('academy_settings_id_check',sql`${t.id}=1`)]);
export const contactMessages = pgTable('contact_messages',{id:serial('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),subject:text('subject').notNull(),message:text('message').notNull(),fingerprint:text('fingerprint').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()},t=>[index('contact_messages_created_idx').on(t.createdAt)]);
export const academyAudit = pgTable('academy_audit',{id:serial('id').primaryKey(),actorId:integer('actor_id').references(()=>users.id,{onDelete:'set null'}),action:text('action').notNull(),resource:text('resource').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()});
export const publicRequestLimits = pgTable('public_request_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull()});

export const academyTestimonials = pgTable('academy_testimonials', {id:serial('id').primaryKey(),name:text('name').notNull(),quote:text('quote').notNull(),language:text('language').notNull(),location:text('location').notNull().default(''),consent:boolean('consent').notNull().default(false),published:boolean('published').notNull().default(false),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()}, t=>[check('academy_testimonials_name_check',sql`char_length(${t.name}) BETWEEN 1 AND 100`),check('academy_testimonials_quote_check',sql`char_length(${t.quote}) BETWEEN 10 AND 2000`),check('academy_testimonials_language_check',sql`${t.language} IN ('ar','en')`),check('academy_testimonials_location_check',sql`char_length(${t.location})<=100`),check('academy_testimonials_check',sql`NOT ${t.published} OR ${t.consent}`)]);

export const pushSubscriptions = pgTable('push_subscriptions', {id:serial('id').primaryKey(),userId:integer('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),endpoint:text('endpoint').notNull().unique(),p256dh:text('p256dh').notNull(),auth:text('auth').notNull(),language:text('language').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()},t=>[index('push_subscription_user_idx').on(t.userId),check('push_language_check',sql`${t.language} IN ('ar','en')`)]);
export const pushDeliveries = pgTable('push_deliveries', {id:bigserial('id',{mode:'number'}).primaryKey(),notificationId:integer('notification_id').notNull().references(()=>notifications.id,{onDelete:'cascade'}),subscriptionId:integer('subscription_id').notNull().references(()=>pushSubscriptions.id,{onDelete:'cascade'}),attempts:integer('attempts').notNull().default(0),status:text('status').notNull().default('pending'),nextAttempt:timestamp('next_attempt',{withTimezone:true}).notNull().defaultNow(),lastError:text('last_error')},t=>[uniqueIndex('push_delivery_unique').on(t.notificationId,t.subscriptionId),index('push_pending_idx').on(t.nextAttempt).where(sql`${t.status}='pending'`)]);

export const accountDetails = pgTable("account_details", {
 userId: integer("user_id").primaryKey().references(()=>users.id,{onDelete:"cascade"}),
 dateOfBirth:date("date_of_birth",{mode:"string"}), city:varchar("city",{length:100}).notNull().default(""),bio:varchar("bio",{length:1000}).notNull().default(""),phone:varchar("phone",{length:30}).notNull().default(""),country:varchar("country",{length:100}).notNull().default(""),timezone:varchar("timezone",{length:80}).notNull().default("UTC"),preferredLanguage:varchar("preferred_language",{length:2}).notNull().default("en"),updatedAt:timestamp("updated_at").notNull().defaultNow()
});

export const accountPreferences=pgTable('account_preferences',{userId:integer('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),emailUpdates:boolean('email_updates').notNull().default(true),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()});
export const emailDeliveries=pgTable('email_deliveries',{payload:jsonb('payload'),id:bigserial('id',{mode:'number'}).primaryKey(),notificationId:integer('notification_id').notNull().unique().references(()=>notifications.id,{onDelete:'cascade'}),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttempt:timestamp('next_attempt',{withTimezone:true}).notNull().defaultNow(),lastError:text('last_error'),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()},t=>[index('email_delivery_pending_idx').on(t.nextAttempt).where(sql`${t.status} in ('pending','sending')`)]);
