import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { useSearch } from 'wouter';
import { useTranslation } from 'react-i18next';
import { ChevronLeft, ChevronRight, CalendarDays } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';

type Session = {id:number;title:string;starts_at:string;ends_at:string;status:string;student_id?:number;kind:'lesson'|'appointment';[key:string]:any};
const dateKey=(date:Date,timezone:string)=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);return ['year','month','day'].map(key=>parts.find(v=>v.type===key)?.value).join('-');};
const dayKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const dateForKey=(key:string)=>new Date(key+'T12:00:00');
const addDays=(date:Date,days:number)=>{const next=new Date(date);next.setDate(next.getDate()+days);return next;};
export function AcademySchedule({lessons,appointments=[],timezone,people=[],admin,renderLesson,renderCreate,renderAppointment}:{lessons:any[];appointments?:any[];timezone:string;people?:any[];admin:boolean;renderLesson:(l:any)=>ReactNode;renderCreate?:()=>ReactNode;renderAppointment?:(a:any)=>ReactNode}) {
  const {t,i18n}=useTranslation(),tr=(k:string)=>t('followup.'+k);
  const [view,setView]=useState<'month'|'week'|'day'|'list'>(()=>window.innerWidth<640?'list':'week'),[anchor,setAnchor]=useState(()=>dateForKey(dateKey(new Date(),timezone))),[type,setType]=useState('all'),[student,setStudent]=useState('all'),[selected,setSelected]=useState<Session|null>(null),[create,setCreate]=useState(false);
  const sessions=useMemo(()=>[...lessons.map(v=>({...v,kind:'lesson' as const})),...appointments.map(v=>({...v,title:tr('assessment'),kind:'appointment' as const}))].filter(v=>v.starts_at&&(type==='all'||v.kind===type)&&(student==='all'||String(v.student_id)===student)),[lessons,appointments,type,student,i18n.language]);
  const search=useSearch();
  const calendarScroll=useRef<HTMLDivElement>(null);
  const openedSearch=useRef<string|null>(null);
  useEffect(()=>{
    const focus=new URLSearchParams(search).get('focus');
    if(!focus?.startsWith('lesson:')) {openedSearch.current=null;return;}
    if(openedSearch.current===search)return;
    const lesson=lessons.find(l=>l.id===Number(focus.split(':')[1]));
    if(lesson?.starts_at){openedSearch.current=search;setSelected({...lesson,kind:'lesson'});setAnchor(dateForKey(dateKey(new Date(lesson.starts_at),timezone)));}
  },[search,lessons,timezone]);
  const first=new Date(anchor.getFullYear(),anchor.getMonth(),1,12),weekStart=addDays(anchor,-((anchor.getDay()+6)%7)),monthStart=addDays(first,-((first.getDay()+6)%7));
  const start=view==='month'?monthStart:view==='week'?weekStart:view==='list'?first:anchor;
  const days=Array.from({length:view==='month'?42:view==='week'?7:view==='list'?new Date(anchor.getFullYear(),anchor.getMonth()+1,0).getDate():1},(_,i)=>addDays(start,i));
  useEffect(()=>{
    if(view!=='week'&&view!=='day')return;
    const from=dayKey(view==='week'?addDays(anchor,-((anchor.getDay()+6)%7)):anchor),to=dayKey(addDays(dateForKey(from),view==='week'?7:1));
    const hours=sessions.filter(v=>{const key=dateKey(new Date(v.starts_at),timezone);return key>=from&&key<to;}).map(v=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:timezone,hour:'2-digit',hourCycle:'h23'}).format(new Date(v.starts_at))));
    const firstHour=hours.length?Math.max(0,Math.min(...hours)-1):9;
    const frame=requestAnimationFrame(()=>{if(calendarScroll.current)calendarScroll.current.scrollTop=firstHour*65;});return()=>cancelAnimationFrame(frame);
  },[view,anchor,sessions,timezone]);
  const byDay=(day:Date)=>sessions.filter(v=>dateKey(new Date(v.starts_at),timezone)===dayKey(day)).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());
  const time=(date:string)=>new Intl.DateTimeFormat(i18n.language,{timeZone:timezone,hour:'2-digit',minute:'2-digit'}).format(new Date(date));
  const move=(direction:number)=>{if(view==='month'||view==='list')setAnchor(new Date(anchor.getFullYear(),anchor.getMonth()+direction,1,12));else setAnchor(addDays(anchor,direction*(view==='week'?7:1)));};
  const heading=anchor.toLocaleDateString(i18n.language,view==='day'?{dateStyle:'full'}:{month:'long',year:'numeric'});
  const event=(session:Session)=> <button key={session.kind+session.id} className={'schedule-event schedule-event-'+session.kind+(session.status==='cancelled'?' schedule-event-cancelled':'')} onClick={()=>setSelected(session)} aria-label={`${tr('open')}: ${session.title} ${time(session.starts_at)}`}><span>{time(session.starts_at)} – {time(session.ends_at)}</span><strong>{session.title}</strong>{admin&&session.student_id&&<small>{people.find(p=>p.id===session.student_id)?.name||''}</small>}<small>{t('p4.states.'+session.status)}</small></button>;
  const current=selected?sessions.find(v=>v.id===selected.id&&v.kind===selected.kind):null;
  return <section className="academy-schedule"><header className="schedule-heading"><div><h2>{tr('scheduleTitle')}</h2><p>{tr('scheduleIntro')}</p></div>{admin&&renderCreate&&<button className="p4-button" onClick={()=>setCreate(true)}><CalendarDays size={18} aria-hidden/>{tr('create')}</button>}</header><div className="schedule-toolbar"><div className="schedule-period"><button onClick={()=>move(-1)} aria-label={tr('previous')}><ChevronLeft size={18}/></button><button onClick={()=>setAnchor(dateForKey(dateKey(new Date(),timezone)))}>{tr('today')}</button><button onClick={()=>move(1)} aria-label={tr('next')}><ChevronRight size={18}/></button><h3>{heading}</h3></div><div className="schedule-modes" role="group" aria-label={tr('scheduleTitle')}>{(['month','week','day','list'] as const).map(mode=><button key={mode} aria-pressed={view===mode} onClick={()=>setView(mode)}>{tr(mode)}</button>)}</div></div><div className="schedule-filters"><label><span className="sr-only">{tr('allTypes')}</span><select value={type} onChange={e=>setType(e.target.value)}><option value="all">{tr('allTypes')}</option><option value="lesson">{tr('lesson')}</option><option value="appointment">{tr('assessment')}</option></select></label>{admin&&<label><span className="sr-only">{tr('studentsTitle')}</span><select value={student} onChange={e=>setStudent(e.target.value)}><option value="all">{tr('all')}</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<span><bdi>{timezone}</bdi></span></div>
    {view==='month'?<div className="schedule-month">{days.slice(0,7).map(day=><div className="schedule-weekday" key={dayKey(day)}>{day.toLocaleDateString(i18n.language,{weekday:'short'})}</div>)}{days.map(day=><div key={dayKey(day)} className={'schedule-month-cell'+(day.getMonth()!==anchor.getMonth()?' is-outside':'')}><button className={'schedule-day-number'+(dayKey(day)===dateKey(new Date(),timezone)?' is-today':'')} onClick={()=>{setAnchor(day);setView('day');}}>{day.toLocaleDateString(i18n.language,{day:'numeric'})}</button>{byDay(day).slice(0,3).map(event)}{byDay(day).length>3&&<button className="schedule-more" onClick={()=>{setAnchor(day);setView('day');}}>+{byDay(day).length-3}</button>}</div>)}</div>:view==='list'?<div className="schedule-list">{days.filter(day=>byDay(day).length).map(day=><section key={dayKey(day)}><h4>{day.toLocaleDateString(i18n.language,{weekday:'long',month:'short',day:'numeric'})}</h4><div>{byDay(day).map(event)}</div></section>)}{!days.some(day=>byDay(day).length)&&<p className="schedule-empty">{tr('noEvents')}</p>}</div>:<div ref={calendarScroll} className="schedule-grid-scroll"><div className={'schedule-time-grid schedule-time-'+view} style={{gridTemplateColumns:`52px repeat(${days.length}, minmax(105px,1fr))`}}><div className="schedule-time-corner"/>{days.map(day=><div className="schedule-time-date" key={dayKey(day)}>{day.toLocaleDateString(i18n.language,{weekday:'short',day:'numeric'})}</div>)}{Array.from({length:24},(_,hour)=><div className="schedule-hour-row" key={hour}><span className="schedule-hour">{String(hour).padStart(2,'0')}:00</span>{days.map(day=><div className="schedule-hour-cell" key={dayKey(day)}>{byDay(day).filter(v=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:timezone,hour:'2-digit',hourCycle:'h23'}).format(new Date(v.starts_at)))===hour).map(event)}</div>)}</div>)}</div></div>}
    <Sheet open={Boolean(current)||create} onOpenChange={open=>{if(!open){setSelected(null);setCreate(false);}}}><SheetContent dir={i18n.dir()} side={i18n.dir()==='rtl'?'left':'right'} overlayClassName="academy-detail-overlay" className="academy-detail-sheet"><SheetHeader className="academy-detail-heading"><SheetTitle>{create?tr('create'):current?.title}</SheetTitle><SheetDescription>{create?tr('scheduleIntro'):current?`${time(current.starts_at)} – ${time(current.ends_at)} · ${timezone}`:''}</SheetDescription></SheetHeader>{create?renderCreate?.():current?.kind==='lesson'?renderLesson(current):current&&renderAppointment?renderAppointment(current):current&&<div className="student-detail-lesson"><p>{new Date(current.starts_at).toLocaleString(i18n.language,{timeZone:timezone})}</p><p>{t('p4.states.'+current.status)}</p>{admin&&<p>{people.find(p=>p.id===current.student_id)?.name}</p>}</div>}</SheetContent></Sheet>
  </section>;
}
