import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { CalendarDays, CheckCheck, ArrowUpRight } from 'lucide-react';
export function LessonCompletion({lessons,attendance=[],timezone='UTC',admin,onOpen,onAttendance}:{lessons:{status:string;starts_at?:string;ends_at?:string;title?:string}[];attendance?:{status:string;session_date:string}[];timezone?:string;admin:boolean;onOpen:()=>void;onAttendance?:()=>void}) {
 const {t,i18n}=useTranslation(),[period,setPeriod]=useState('all'),tr=(k:string)=>t('refinement.'+k);
 const now=new Date();
 const localKey=(d:Date)=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);return ['year','month','day'].map(k=>p.find(v=>v.type===k)?.value).join('-');};
 const today=localKey(now),startWeek=new Date(today+'T12:00:00Z');startWeek.setUTCDate(startWeek.getUTCDate()-((startWeek.getUTCDay()+6)%7));
 const endWeek=new Date(startWeek);endWeek.setUTCDate(endWeek.getUTCDate()+6);
 const inPeriod=(value?:string)=>{if(period==='all')return true;if(!value)return false;const d=new Date(value);if(Number.isNaN(d.getTime()))return false;const key=localKey(d);return period==='month'?key.slice(0,7)===today.slice(0,7):key>=startWeek.toISOString().slice(0,10)&&key<=endWeek.toISOString().slice(0,10);};
 const filtered=lessons.filter(l=>inPeriod(l.starts_at)),completed=filtered.filter(l=>l.status==='completed').length,remaining=filtered.filter(l=>l.status==='scheduled').length,total=completed+remaining,percent=total?completed/total*100:0;
 const records=attendance.filter(a=>inPeriod(a.session_date)),attended=records.filter(a=>['present','late'].includes(a.status)).length;
 const upcoming=lessons.filter(l=>l.status==='scheduled'&&l.starts_at&&new Date(l.starts_at).getTime()>=now.getTime()).sort((a,b)=>+new Date(a.starts_at!)-+new Date(b.starts_at!))[0];
 const format=(v:number)=>new Intl.NumberFormat(i18n.language).format(v),label=total?t('workspace.completionCounts',{completed:format(completed),remaining:format(remaining)}):t('workspace.completionEmpty');
 return <section className="dash-panel dash-completion"><h2>{t('workspace.'+(admin?'academyCompletion':'lessonCompletion'))}</h2><div className="dash-progress-period" role="group" aria-label={tr('period')}>{['all','month','week'].map(key=><button key={key} type="button" aria-pressed={period===key} onClick={()=>setPeriod(key)}>{tr('progress'+key[0].toUpperCase()+key.slice(1))}</button>)}</div><button className="dash-completion-open" type="button" onClick={onOpen} aria-label={tr('viewSchedule')}><div className="dash-completion-ring"><svg viewBox="0 0 120 120" role="img" aria-label={label}><circle cx="60" cy="60" r="49" className="dash-ring-track"/><circle cx="60" cy="60" r="49" className="dash-ring-value" style={{opacity:completed?1:0}} pathLength="100" strokeDasharray={percent+' 100'} transform="rotate(-90 60 60)"/></svg><span aria-hidden="true"><strong>{total?new Intl.NumberFormat(i18n.language,{style:'percent',maximumFractionDigits:0}).format(percent/100):'—'}</strong><small>{t('workspace.completed')}</small></span></div></button><dl className="dash-ring-legend"><div><dt>{t('workspace.completed')}</dt><dd>{format(completed)}</dd></div><div><dt>{t('workspace.remaining')}</dt><dd>{format(remaining)}</dd></div></dl><button className="dash-progress-attendance" onClick={onAttendance||onOpen}><CheckCheck size={18} aria-hidden/><span>{tr('attendance')}</span><strong>{records.length?new Intl.NumberFormat(i18n.language,{style:'percent',maximumFractionDigits:0}).format(attended/records.length):'—'}</strong><ArrowUpRight size={16} aria-hidden/></button><button className="dash-progress-next" onClick={onOpen}><CalendarDays size={18} aria-hidden/><span><small>{tr('nextLesson')}</small><strong>{upcoming?.title||tr('noNext')}</strong>{upcoming?.starts_at&&<time>{new Intl.DateTimeFormat(i18n.language,{timeZone:timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(upcoming.starts_at))}</time>}</span></button><p>{tr('progressNote')}</p></section>;
}
