import { StudentOverview } from './StudentOverview';
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useSearch } from 'wouter';
import { Search, ChevronRight, CalendarDays } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { AccountAvatar } from './AccountAvatar';
import { LessonActions, FollowupHistory } from './LessonFollowup';
export function StudentsWorkspace({data,date,program,onDone,onStatus,busy,updates,updatesError}:{data:any;date:(s:string)=>string;program:(id:number)=>string;onDone:()=>void;onStatus:(p:any)=>void;busy:boolean;updates:any[];updatesError:string}) {
  const {t,i18n}=useTranslation(),tr=(key:string)=>t('followup.'+key);
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selectedId,setSelectedId]=useState<number|null>(null),[page,setPage]=useState(1);
  const people=useMemo(()=>data.people.filter((p:any)=>(filter==='all'||p.status===filter)&&`${p.name} ${p.email}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[data.people,query,filter]);
  useEffect(()=>{setPage(1);},[query,filter]);
  const search=useSearch();
  useEffect(()=>{const focus=new URLSearchParams(search).get('focus');if(focus?.startsWith('student:'))setSelectedId(Number(focus.split(':')[1]));},[search]);
  const selected=data.people.find((p:any)=>p.id===selectedId);
  const lessons=(id:number)=>data.lessons.filter((l:any)=>l.student_id===id).sort((a:any,b:any)=>new Date(b.starts_at).getTime()-new Date(a.starts_at).getTime());
  const upcoming=(id:number)=>lessons(id).filter((l:any)=>l.status==='scheduled'&&new Date(l.ends_at).getTime()>Date.now()).reverse()[0];
  const enrollmentNames=(id:number)=>Array.from(new Set(data.enrollments.filter((e:any)=>e.student_id===id&&e.status==='active').map((e:any)=>program(e.program_id))));
  const totalPages=Math.max(1,Math.ceil(people.length/8)),current=Math.min(page,totalPages);
  return <section className="students-workspace"><header className="students-heading"><div><h2>{tr('studentsTitle')}</h2><p>{tr('studentsIntro')}</p></div><span className="students-count">{data.people.length}</span></header><div className="students-toolbar"><label className="students-search"><Search size={19} aria-hidden/><span className="sr-only">{tr('search')}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr('search')}/></label><label><span className="sr-only">{tr('all')}</span><select value={filter} onChange={e=>setFilter(e.target.value)}>{['all','active','invited','suspended'].map(k=><option key={k} value={k}>{tr(k)}</option>)}</select></label></div>
    <div className="student-card-grid">{people.slice((current-1)*8,current*8).map((p:any)=>{const next=upcoming(p.id);return <button type="button" key={p.id} data-search-target={'student:'+p.id} className="student-summary-card" onClick={()=>setSelectedId(p.id)}><span className="student-card-top"><span className="student-avatar"><AccountAvatar user={p}/></span><span className={'student-status student-status-'+p.status}>{t('p4.states.'+p.status)}</span></span><strong>{p.name}</strong><span className="student-email" dir="ltr">{p.email}</span><span className="student-course-tags">{enrollmentNames(p.id).map(name=><span key={String(name)}>{String(name)}</span>)}</span><span className="student-next"><CalendarDays size={16} aria-hidden/><span>{next?date(next.starts_at):tr('noNext')}</span></span><span className="student-view">{tr('details')}<ChevronRight size={16} aria-hidden/></span></button>;})}</div>{!people.length&&<p className="p4-card">{tr('empty')}</p>}<nav className="students-pagination" aria-label={tr('studentsTitle')}><button disabled={current<=1} onClick={()=>setPage(current-1)} aria-label={tr('previous')}>‹</button><span>{current} / {totalPages}</span><button disabled={current>=totalPages} onClick={()=>setPage(current+1)} aria-label={tr('next')}>›</button></nav>
    <Sheet open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelectedId(null);}}><SheetContent side={i18n.dir()==='rtl'?'left':'right'} overlayClassName="academy-detail-overlay" className="academy-detail-sheet" dir={i18n.dir()}>{selected&&<><SheetHeader className="academy-detail-heading"><SheetTitle>{t('polish.personalRecord')}</SheetTitle><SheetDescription>{selected.name}</SheetDescription></SheetHeader><p className="student-record-hint">{t("polish.personalRecordHint")}</p><StudentOverview studentId={selected.id} revision={data} onLessons={()=>document.getElementById("student-record-lessons")?.scrollIntoView({behavior:"smooth",block:"start"})} onAttendance={()=>document.getElementById("student-record-attendance")?.scrollIntoView({behavior:"smooth",block:"start"})}/><section><h3>{tr('programs')}</h3><div className="student-course-tags">{enrollmentNames(selected.id).map(name=><span key={String(name)}>{String(name)}</span>)}</div>{!enrollmentNames(selected.id).length&&<p>{tr('noPrograms')}</p>}</section>{['active','suspended'].includes(selected.status)&&<button disabled={busy} className="p4-button" onClick={()=>onStatus(selected)}>{t('p4.'+(selected.status==='active'?'suspend':'activate'))}</button>}<section id="student-record-lessons"><h3>{tr('lessons')}</h3>{lessons(selected.id).map((l:any)=><article className="student-detail-lesson" key={l.id}><div className="p4-row"><h4>{l.title}</h4><span className="p4-badge">{t('p4.states.'+l.status)}</span></div><p>{date(l.starts_at)}</p><LessonActions lesson={l} onDone={onDone}/></article>)}{!lessons(selected.id).length&&<p>{tr('noNext')}</p>}</section><section id="student-record-attendance"><h3>{tr('attendance')}</h3>{data.attendance.filter((a:any)=>a.student_id===selected.id).map((a:any)=><article className="student-detail-lesson" key={a.id}><p>{date(a.session_date)}</p><span className="p4-badge">{t('p4.states.'+a.status)}</span>{a.notes&&<p>{a.notes}</p>}</article>)}{!data.attendance.some((a:any)=>a.student_id===selected.id)&&<p>{t('p4.empty')}</p>}</section><FollowupHistory updates={updates} error={updatesError} studentId={selected.id}/></>}</SheetContent></Sheet>
  </section>;
}
